import React from 'react';

import strings from '../components/strings';
import MainContainer from '../components/mainContainer';

import Table from '../components/table';

import '../sass/views/home.scss';

class Home extends React.PureComponent {
  render() {
    const data = [{
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '1',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '1',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 1,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }, {
      bookingId: 2,
      name: 'Jose',
      bookingTime: '1',
      streetAddress: '1',
      bookingPrice: '11',
    }];
    return (
      <MainContainer content={<Table data={data} />} label={strings.home} />
    );
  }
}

export default Home;
